# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Math-IRR
version:      0.06
version_from: lib/Finance/Math/IRR.pm
installdirs:  site
requires:
    Date::Calc:                    5.4
    Math::Polynom:                 0.06
    Scalar::Util:                  1.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
